# Generated by Django 4.1.7 on 2023-03-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(default='users/pictures/user.png', upload_to='users/pictures'),
        ),
    ]
