# Generated by Django 4.1.7 on 2023-03-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
