# Generated by Django 4.1.7 on 2023-03-09 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_profilemodel_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Cumpleaños'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(default='users/pictures/user.png', upload_to='users/pictures', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
