# Generated by Django 4.1.7 on 2023-03-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profilemodel_followers'),
        ('posts', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsmodel',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postsmodel', verbose_name='Publicacion'),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profilemodel', verbose_name='Perfil'),
        ),
    ]
